#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scheduler - Scheduled tasks for AI Employee.

This module provides scheduled task functionality including:
- Daily briefings
- Weekly CEO briefings
- Periodic task processing
- Cron-like scheduling

Usage:
    python scheduler.py <vault_path> <task_type> [options]

Examples:
    # Run daily briefing at 8 AM
    python scheduler.py ../ daily_briefing --hour 8

    # Run weekly CEO briefing on Sunday at 7 AM
    python scheduler.py ../ weekly_briefing --day sunday --hour 7

    # Process all pending tasks
    python scheduler.py ../ process_pending
"""

import sys
import json
import subprocess
import argparse
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional, List, Dict, Any


class Scheduler:
    """
    Task scheduler for AI Employee.
    
    Handles scheduled tasks like daily briefings, weekly reports,
    and periodic task processing.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the scheduler.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.briefings_folder = self.vault_path / 'Briefings'
        self.done_folder = self.vault_path / 'Done'
        self.logs_folder = self.vault_path / 'Logs'
        self.business_goals = self.vault_path / 'Business_Goals.md'
        self.dashboard = self.vault_path / 'Dashboard.md'
        
        # Ensure folders exist
        self.briefings_folder.mkdir(parents=True, exist_ok=True)
        
        # Setup logging
        self.logger = self._setup_logging()
    
    def _setup_logging(self):
        """Setup logging configuration."""
        import logging
        
        log_file = self.logs_folder / f'scheduler_{datetime.now().strftime("%Y-%m-%d")}.log'
        
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(log_file),
                logging.StreamHandler()
            ]
        )
        
        return logging.getLogger('Scheduler')
    
    def run_daily_briefing(self, hour: int = 8) -> Path:
        """
        Generate a daily briefing.
        
        Args:
            hour: Hour for the briefing (default: 8)
        
        Returns:
            Path: Path to created briefing file
        """
        self.logger.info(f'Generating daily briefing for {hour}:00')
        
        today = datetime.now()
        briefing_date = today.strftime('%Y-%m-%d')
        filename = f'Daily_Briefing_{briefing_date}.md'
        filepath = self.briefings_folder / filename
        
        # Get yesterday's completed tasks
        completed_tasks = self._get_completed_tasks(days=1)
        
        # Get pending tasks
        pending_tasks = self._get_pending_tasks()
        
        # Get recent logs
        recent_logs = self._get_recent_logs()
        
        content = f'''---
type: daily_briefing
date: {briefing_date}
generated: {datetime.now().isoformat()}
---

# Daily Briefing - {today.strftime('%A, %B %d, %Y')}

## Summary

Generated at {today.strftime('%I:%M %p')}

---

## Completed Tasks (Last 24 Hours)

{self._format_task_list(completed_tasks)}

---

## Pending Tasks

{self._format_task_list(pending_tasks)}

---

## Recent Activity

{self._format_logs(recent_logs)}

---

## Today's Focus

*Add your focus areas for today.*

---

## Notes

*Add any additional notes.*

---
*Generated by AI Employee Scheduler*
'''
        
        filepath.write_text(content)
        self.logger.info(f'Daily briefing created: {filename}')
        
        return filepath
    
    def run_weekly_briefing(self, day: str = 'monday') -> Path:
        """
        Generate a weekly CEO briefing.
        
        Args:
            day: Day of the week (default: monday)
        
        Returns:
            Path: Path to created briefing file
        """
        self.logger.info(f'Generating weekly briefing for {day}')
        
        today = datetime.now()
        briefing_date = today.strftime('%Y-%m-%d')
        filename = f'Weekly_Briefing_{briefing_date}.md'
        filepath = self.briefings_folder / filename
        
        # Get last 7 days of completed tasks
        completed_tasks = self._get_completed_tasks(days=7)
        
        # Get pending tasks
        pending_tasks = self._get_pending_tasks()
        
        # Get business goals
        goals_content = self._read_file_safe(self.business_goals)
        
        # Calculate metrics
        total_completed = len(completed_tasks)
        total_pending = len(pending_tasks)
        
        content = f'''---
type: weekly_briefing
date: {briefing_date}
generated: {datetime.now().isoformat()}
period_start: {(today - timedelta(days=7)).strftime('%Y-%m-%d')}
period_end: {today.strftime('%Y-%m-%d')}
---

# Weekly CEO Briefing

## Executive Summary

**Period:** {(today - timedelta(days=7)).strftime('%b %d')} - {today.strftime('%b %d, %Y')}

| Metric | Value |
|--------|-------|
| Tasks Completed | {total_completed} |
| Tasks Pending | {total_pending} |
| Completion Rate | {self._calc_completion_rate(total_completed, total_pending)}% |

---

## Completed Tasks This Week

{self._format_task_list(completed_tasks)}

---

## Pending Tasks

{self._format_task_list(pending_tasks)}

---

## Business Goals Progress

{goals_content[:2000] if goals_content else "No business goals found."}

---

## Proactive Suggestions

*AI-generated suggestions will appear here after analysis.*

### Cost Optimization
*Review subscriptions and recurring expenses.*

### Upcoming Deadlines
*Add any upcoming deadlines.*

---

## Notes

*Add any additional notes for the CEO.*

---
*Generated by AI Employee Scheduler*
'''
        
        filepath.write_text(content)
        self.logger.info(f'Weekly briefing created: {filename}')
        
        return filepath
    
    def process_pending_tasks(self):
        """
        Process all pending tasks in Needs_Action folder.
        """
        self.logger.info('Processing pending tasks')
        
        needs_action = self.vault_path / 'Needs_Action'
        
        if not needs_action.exists():
            self.logger.warning('Needs_Action folder not found')
            return
        
        # Get all .md files
        pending_files = list(needs_action.glob('*.md'))
        
        if not pending_files:
            self.logger.info('No pending tasks found')
            return
        
        self.logger.info(f'Found {len(pending_files)} pending task(s)')
        
        # Start orchestrator for each task
        for task_file in pending_files:
            self.logger.info(f'Processing: {task_file.name}')
            
            # Read task content
            content = self._read_file_safe(task_file)
            
            # Check if it's an approval request
            if 'type: approval_request' in content:
                self.logger.info(f'Skipping approval request: {task_file.name}')
                continue
            
            # Process with orchestrator logic
            # (This would typically call the orchestrator)
            self.logger.info(f'Task queued: {task_file.name}')
        
        self.logger.info('Task processing complete')
    
    def _get_completed_tasks(self, days: int = 1) -> List[Dict]:
        """Get completed tasks from the last N days."""
        tasks = []
        
        if not self.done_folder.exists():
            return tasks
        
        cutoff = datetime.now() - timedelta(days=days)
        
        for f in self.done_folder.glob('*.md'):
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                if mtime >= cutoff:
                    tasks.append({
                        'name': f.name,
                        'time': mtime.strftime('%Y-%m-%d %H:%M')
                    })
            except:
                continue
        
        return tasks
    
    def _get_pending_tasks(self) -> List[Dict]:
        """Get pending tasks from Needs_Action folder."""
        tasks = []
        
        needs_action = self.vault_path / 'Needs_Action'
        if not needs_action.exists():
            return tasks
        
        for f in needs_action.glob('*.md'):
            # Skip approval requests
            content = self._read_file_safe(f)
            if 'type: approval_request' in content:
                continue
            
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                tasks.append({
                    'name': f.name,
                    'time': mtime.strftime('%Y-%m-%d %H:%M')
                })
            except:
                continue
        
        return tasks
    
    def _get_recent_logs(self, count: int = 10) -> List[Dict]:
        """Get recent log entries."""
        logs = []
        
        today_log = self.logs_folder / f'{datetime.now().strftime("%Y-%m-%d")}.json'
        
        if today_log.exists():
            try:
                data = json.loads(today_log.read_text())
                logs = data[-count:] if isinstance(data, list) else []
            except:
                pass
        
        return logs
    
    def _format_task_list(self, tasks: List[Dict]) -> str:
        """Format task list as markdown."""
        if not tasks:
            return '*No tasks.*'
        
        lines = []
        for task in tasks[:20]:  # Limit to 20 tasks
            lines.append(f"- [ ] {task['name']} ({task['time']})")
        
        if len(tasks) > 20:
            lines.append(f'- ... and {len(tasks) - 20} more')
        
        return '\n'.join(lines)
    
    def _format_logs(self, logs: List[Dict]) -> str:
        """Format logs as markdown."""
        if not logs:
            return '*No recent activity.*'
        
        lines = []
        for log in logs[-10:]:
            op = log.get('operation', 'unknown')
            ts = log.get('timestamp', '')
            lines.append(f"- {op} at {ts}")
        
        return '\n'.join(lines)
    
    def _calc_completion_rate(self, completed: int, pending: int) -> int:
        """Calculate completion rate percentage."""
        total = completed + pending
        if total == 0:
            return 0
        return int((completed / total) * 100)
    
    def _read_file_safe(self, filepath: Path) -> str:
        """Safely read a file."""
        try:
            return filepath.read_text()
        except:
            return ""


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description='AI Employee Scheduler')
    parser.add_argument('vault_path', help='Path to the Obsidian vault')
    parser.add_argument('task_type', choices=['daily_briefing', 'weekly_briefing', 'process_pending'],
                       help='Type of scheduled task')
    parser.add_argument('--hour', type=int, default=8, help='Hour for daily briefing')
    parser.add_argument('--day', default='monday', help='Day for weekly briefing')
    
    args = parser.parse_args()
    
    vault = Path(args.vault_path)
    if not vault.exists():
        print(f"Error: Vault path does not exist: {args.vault_path}")
        sys.exit(1)
    
    scheduler = Scheduler(str(vault))
    
    if args.task_type == 'daily_briefing':
        scheduler.run_daily_briefing(args.hour)
    elif args.task_type == 'weekly_briefing':
        scheduler.run_weekly_briefing(args.day)
    elif args.task_type == 'process_pending':
        scheduler.process_pending_tasks()
    
    print('Task completed successfully!')


if __name__ == '__main__':
    main()
