{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "todo-chatbot.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    # Route frontend traffic
    - matches:
      - path:
          type: PathPrefix
          value: "/"
      backendRefs:
        - name: {{ $fullName }}-frontend
          port: {{ .Values.frontend.service.port }}
          weight: 1
    # Route API traffic to backend
    - matches:
      - path:
          type: PathPrefix
          value: "/api"
      backendRefs:
        - name: {{ $fullName }}-backend
          port: {{ .Values.backend.service.port }}
          weight: 1
{{- end }}
